language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '0.12'
  - '4.2'
  - '5.1'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower@1.7.1 gulp@3.9.0 firebase-tools@2.2.0
  - bower i
script:
  - ./travis-runner.sh
env:
  global:
    - secure: "cluWtV0MdLQB6YVmvctf//X6XJFZbo7FLnIbh8G8xQ+0IFM8o/2Ggdl53lTdpjBkL80uLcLe9bqABC68QzujUA4vlxUC5am+x14uXI8lYrDVjPWiKmVwxmee4FpbEQq7zBg7bW58ZQUnnsJvuzBv46DpebKNl469qYOrnQF79sDnYgi4kLxuCUcgv1Rlo/j/aABxgN0cZePHlcASxTvkHdhaMUp0G00B7nZEG6AuJmNaK8Suib9ZEq34w8BEU5kYk0ed5u9lhTAtViS5htH9Z+xwysme42lXWAYk+UlMB1VHiQ3yZX30/dGQHGe7BV2HajJf1MyrM1dmZIR7JeFuhjXeAXn9pWiET8vCQqw1C246aKoNqo7uo/TkPxY1exJLh3CjpFO5Gt1GikXqcf4UghuRCTgXJZPCMSHkzwfYevSNjhe7TZoUPtVE+sJDnImfF9hi6aFnTv9F+LD9S2HH+P+1EdqkKX0YzwY583FQmgVqqS+Smi8konyC0fQIACQvLlKsBJEFQOvg4nGvOhDzA8JTblAOvi7p+rCZz6kVMf36/MaUVASK18XYzuWDopb8qpSHnpQKH6n3qf1EcnP5cIwpbSr3tadjNef24cmPmxtfEqZnYM+EZ+nwCf+iYjOUmZ7r+5U4WD8E3mFN3rtfdAKLDNSnm6zNPBs8Ly9IDyE="
