language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '0.12'
  - '4.2'
  - '5.1'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower@1.7.1 gulp@3.9.0 firebase-tools@2.2.0
  - bower i
script:
  - ./travis-runner.sh
env:
  global:
    - secure: "pSoI66h28SNFQ+VzCRpioD4y6yGH/XkNLuw0OQxDBbK9JK6/bd2b5UAn6YzsLjpEuIo2DmuEtoDSbuiontR7M+2hbguVLOELPLZoKtc81wxjNLCggEbwA6mNJf8/mJaddb1Asm7YmHR53fb8IBQxEK6NdfB6/0bPstgnBZKjk+sBVOGWiYF/ixp03RN33r2cM/3v65aSOxMajALV1X1c7rqazk84TI/9KYQLUvUefvgboEcofJ3RoIZFCGKhfbfa+xDAcjNClqeKB5OqqjJlPuDBWfYtdfZt2AtkfS1vmqfzJHFMFzrazPlN8+u/Gv1tpahsG57wGVwlJS3pat4kG58n25aCtB2tNpWToawNe0qDwlgV9ec+qsl1Tb8JMIkQqEmA31W0taQ+jrdet1psN5VX+PF/hS7t7b9mSWgFS18dKbJfq8NpgI0Lfmw8tUcGQuam3VUujdUmyXR7HvOWZlfFbnRW+ehl0B4qFGwY5C0BFyoInBAWd9PtOR/1UCR6k1yGl7r57Uifk91YI0YpqxnC9Z8KiqPfm8xahrXnXPbrHubI0T2OMO99KhZ2TVtrRazDCkKIx5v3siOtTGmfPBaP/2lrLKmAeSfELvxwgLXXkC9TNB/zOELnHT/1rg+hIL09k4GNaCAx9xg/9sfxUOhMbL9/6DmsWltri82vIJk=" 
